# Title and subheading for your site. Used on the home page and in page
# titles.
#
title: "Misha Reyzlin"
subtitle: ""

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
author:
  name: Misha Reyzlin
  uri: http://mishareyzlin.com
  email: hello@mishareyzlin.com

theme: mr
disqus_short_name: mreyzlin
# content folder (should contain pages and attachments folders and optional menu.txt)
content: content

# cache
#     Set it to true if you'd like Nesta to cache your pages in ./public.
#     Useful if you're deploying Nesta with a proxy server such as Nginx,
#     but not in the least bit helpful if your pages are dynamic, or you're
#     deploying Nesta to Heroku.
#
cache: false

# Overriding "cache" and "content" in production is recommended if you're
# deploying Nesta to your own server (but see the deployment documentation
# on the Nesta site). Setting google_analytics_code in production is
# recommended regardless of how you're deploying (if you have a GA account!).
#
# Don't forget to uncomment the "production:" line too...

# production:
#   cache: true    
#   content: /var/apps/nesta/shared/content
#   google_analytics_code: "UA-???????-?"
